#!/bin/bash

# Usage: ./build.sh [--platform linux|windows] [--api-host URL] [--api-key KEY]

SCRIPT_DIR="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" &>/dev/null && pwd)"

# Default values
PLATFORM="linux"
API_HOST="http://localhost:8080"
API_KEY=""
BUILD_BOTH=false

# Parse command line arguments
while [[ $# -gt 0 ]]; do
    case $1 in
        --platform)
            PLATFORM="$2"
            shift 2
            ;;
        --api-host)
            API_HOST="$2"
            shift 2
            ;;
        --api-key)
            API_KEY="$2"
            shift 2
            ;;
        -h|--help)
            echo "Usage: ./build.sh [OPTIONS]"
            echo "Options:"
            echo "  --platform linux|windows    Build for specific platform (default: linux)"
            echo "  --api-host URL             Set default API host (default: http://localhost:8080)"
            echo "  --api-key KEY              Set default API key (default: empty)"
            echo "  -h, --help                 Show this help message"
            exit 0
            ;;
        *)
            echo "Unknown option: $1"
            exit 1
            ;;
    esac
done

# Create dist directory if it doesn't exist
mkdir -p dist

# Create build_config.py from template
echo "Creating build configuration..."
cat > build_config.py << EOF
# This file is auto-generated by the build script
# Default API configuration

DEFAULT_API_HOST = "$API_HOST"
DEFAULT_API_KEY = "$API_KEY"
EOF

echo "Default API Host: $API_HOST"
if [ -n "$API_KEY" ]; then
    echo "Default API Key: ${API_KEY:0:8}..."
else
    echo "Default API Key: (empty)"
fi

build_platform() {
    local platform=$1
    local docker_target="${platform}-builder"
    
    echo ""
    echo "========================================"
    echo "Building for $platform..."
    echo "========================================"
    
    # Build Docker image
    docker build \
        --target "$docker_target" \
        --build-arg "DEFAULT_API_HOST=$API_HOST" \
        --build-arg "DEFAULT_API_KEY=$API_KEY" \
        -t "isbn_lookup_excel_desktop_ui_builder_$platform" .
    
    # Run the builder container
    if [ "$platform" = "linux" ]; then
        docker run -v "$SCRIPT_DIR:/src/" --rm "isbn_lookup_excel_desktop_ui_builder_$platform" \
            -c "cd /src && pyinstaller --onefile --windowed --add-data 'build_config.py:.' isbn_lookup_excel_desktop_ui.py && { rm -r /src/build && chmod 777 /src/dist/* 2>/dev/null || :; }"
        
        # Copy the executable to dist directory
        if [ -f "dist/isbn_lookup_excel_desktop_ui" ]; then
            mv "dist/isbn_lookup_excel_desktop_ui" "dist/isbn_lookup_excel_desktop_ui_${platform}"
            echo "Linux executable created: dist/isbn_lookup_excel_desktop_ui_${platform}"
        fi
    else
        docker run -v "$SCRIPT_DIR:/src/" --rm "isbn_lookup_excel_desktop_ui_builder_$platform" \
            -c "cd /src && wine pyinstaller --onefile --windowed --add-data 'build_config.py:.' isbn_lookup_excel_desktop_ui.py && { rm -r /src/build && chmod 777 /src/dist/* 2>/dev/null || :; }"
        
        # Copy the executable to dist directory
        if [ -f "dist/isbn_lookup_excel_desktop_ui.exe" ]; then
            mv "dist/isbn_lookup_excel_desktop_ui.exe" "dist/isbn_lookup_excel_desktop_ui_${platform}.exe"
            echo "Windows executable created: dist/isbn_lookup_excel_desktop_ui_${platform}.exe"
        fi
    fi
}

# Build for selected platform
build_platform "$PLATFORM"

# Cleanup
if [ -f "build_config.py" ]; then
    rm "build_config.py"
fi

echo ""
echo "Build completed!"
echo "Output files in dist/:"
ls -la dist/ 2>/dev/null || echo "dist/ directory is empty"